name: flutter_cluster_dashboard
description: Instrument Cluster demo app using Flutter for AGL

publish_to: 'none'
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# packages used
  flutter_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5
  hooks_riverpod: ^1.0.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.17.0
  http: ^1.2.1
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cert/
    - images/